### ISSUE TITLE
DeZog timeout when connecting to CSpect

### ISSUE THREAD

**Issue by tomaz** [maziac/DeZogPlugin#3]
After upgrading to DeZog 2.0 and DeZogPlugin 2.0.0 I can no longer connect to CSpect (2.13.00) from VSCode. Also don't see any line mentioning plugin has started, which explains timeout, but am left clueless as to why exactly it doesn't work. I updated launch.json according to migration guide... Is there any way I can debug this?

**Comment by maziac** [comment]
After you start CSpect (like so):
![Bildschirmfoto 2021-01-05 um 09 45 54](https://user-images.githubusercontent.com/3081973/103625121-cf53b880-4f3a-11eb-9aee-bd465d09b80c.jpg)

you should see a line telling that the DeZog plugin was started:
![Bildschirmfoto 2021-01-05 um 09 46 07](https://user-images.githubusercontent.com/3081973/103625144-d7abf380-4f3a-11eb-8fb1-b47da48d9e8a.jpg)

If you can't see it the plugin has not started and (as you already mentioned) DeZog can't connect.

Please check that the plugin is really located in the CSpect root directory.
Maybe you used a softlink and forgot to update the link.

**Comment by tomaz** [comment]
Thanks for quick reply! Install location is correct, tripple checked. I don't see any output whatsoever though in console though (not even `CSpect start`). But maybe that's how it works in Windows in general (PowerShell)

**Comment by kborowinski** [comment]
@tomaz On Windows you **can't** see the *CSpect* console output by default as *CSpect* starts new process. However you can use following trick to redirect the output to file:

![image](https://user-images.githubusercontent.com/16168755/103639014-fe275a00-4f4d-11eb-8241-4cb34dca65df.png)

**Comment by tomaz** [comment]
Thanks @kborowinski now I can see what the issue is - seems like for some reason port is already taken. Not sure why, but at least I have starting point for further debugging...

```
#CSpect Start
Next ROM enabled
Error loading ROM: Could not find file 'c:\Users\Tomaz\Documents\Projects\Retro\ZX\Tools\CSpect\enNextMf.rom'.
Dezog Plugin: v2.0.0.34763 started. DZRP v2.0.0.
Dezog Plugin: System.Net.Sockets.SocketException (0x80004005): Only one usage of each socket address (protocol/network address/port) is normally permitted
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at DeZogPlugin.CSpectSocket.StartListening()
Joystick added: 0
Dezog Plugin: Terminated.
```

**Comment by maziac** [comment]
You can also specify a different port.
But you need to do it in 2 places:
- DeZog/vscode: launch.json
- CSpect DeZogPlugin: In CSpect root directory add a DeZogPlugin.dll.config with similar contents (change your port of course):
~~~
<?xml version="1.0" encoding="utf-8"?>
<Settings xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Port>11000</Port>
</Settings>
~~~

**Comment by tomaz** [comment]
Allright, changing port worked! Still not sure why 11000 was taken, it should be free, but then again, who knows... Thank you all for feedback! Closing this issue...
